### PR TITLE
davepacheco/jsstyle#24 Escape more opening curly brackets in regexes

### PR DESCRIPTION
**Pull request by melloc**

### CODE REVIEW

**Comment by melloc** [comment]
To test this, I ran `make check-jsstyle` in sdc-napi, sdc-fwapi, and node-cueball on Mac OS X (Perl 5.26.1) and on SmartOS (Perl 5.22.1).

**Comment by melloc** [comment]
I also fixed a regex that meant to reference `$special`. To test it out, I wrote the following program:

```js
function a()
{
	doThing(); if (n)
	{
		a = 9;
	}
}
```

And ran:

```shell
% ./jsstyle -c -o strict-indent=1,continuation-at-front=1 ./foo.js
./foo.js: 3: if/for/while/switch not started on its own line
./foo.js: 4: left brace starting a line
```

Unfortunately, moving the brace onto the same line as the if defeats this check, due to [this return](https://github.com/davepacheco/jsstyle/blob/b9f50929ee2df140fd2d111f053b20593e068cdc/jsstyle#L817).

**Comment by KodyKantor** [comment]
This change looks good to me! Sorry for the delay in commenting here.

**Comment by melloc** [comment]
Here's a test program that hits all of the changed lines:

```javascript
function foo()
{
	if (true){

	}

	doThing(); if (true)
	{

	}

	{ console.log('hello');
	}

	var a =
		{ }
}
```

Running current master on the program:

```
% ./jsstyle -c -o strict-indent=1 foo.js
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/({|\(){ <-- HERE / at ./jsstyle line 675.
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/(?:(?:\b(?:enum|struct|union)\s*[^\{]*)|(?:\s+=\s*)){ <-- HERE / at ./jsstyle line 793.
foo.js: 4: missing space before left brace
foo.js: 9: left brace starting a line
foo.js: 13: stuff after {
```

Some of the modified lines (lines 680, 794, 817, 824) don't produce Perl warnings, but they are hit by this input program, and do work correctly before and after adding the escape.

Running with the new changes:

```
% ./jsstyle -c -o strict-indent=1 foo.js
foo.js: 4: missing space before left brace
foo.js: 8: if/for/while/switch not started on its own line
foo.js: 9: left brace starting a line
foo.js: 13: stuff after {
```

**Pull request merged**
